server:
  port: 9585

management:
  server.port: 9586
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers: localhost:9092

# This the mapped ip:port for inter instance communication.
# This value should (will) be injected based on evn variables. Those variables will be defined by orchestration tool environment variables
kafka:
  streams:
    server.config:
      app-ip: localhost
      app-port: ${server.port}
  topic-partitions:
    eventTopic: '8:3'
    changeLogTopic: '8:3'

---
spring:
  profiles: local

kafka:
  topic-partitions:
    eventTopic: '1:1'
    changeLogTopic: '1:1'


---
spring:
  profiles: nomad

eureka.client.serviceUrl.defaultZone: "http://${service.registry.server.ip}:${service.registry.server.port}/eureka/"
---
spring:
  profiles:
    - docker-compose
