server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      - defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"

---
spring:
  profiles: nomad

eureka:
  instance:
    hostname: ${nomad.host.ip}
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      - defaultZone: "http://${nomad.host.ip}:${nomad.host.port}/eureka/"
