server:
  port: 8081

wonderland.hello.prefix: NotFromConfigServer

spring:
  kafka:
    bootstrap-servers:
      - "localhost:9092"
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    retries: 3
    acks: all

  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672

topic-defs:
  messageEvents: '1:1'

---
spring:
  profiles: nomad


topic-defs:
  messageEvents: '3:3'

---
spring:
  profiles:
    - docker_compose

topic-defs:
  messageEvents: '2:3'