server:
  port: 8081

wonderland.hello.prefix: NotFromConfigServer
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers:
      - "localhost:9092"
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    retries: 3
    acks: all

topic-defs:
  messageEvents: '1:1'

---
spring:
  profiles: nomad


eureka.client.serviceUrl.defaultZone: "http://${service.registry.server.ip}:${service.registry.server.port}/eureka/"

topic-defs:
  messageEventTopicDefinition: '3:3'

---
spring:
  profiles:
    - docker-compose

topic-defs:
  messageEventTopicDefinition: '2:3'