server:
  port: 8081

wonderland.hello.prefix: NotFromConfigServer
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring.kafka.consumer:
  group-id: ${spring.application.name}
  auto-offset-reset: earliest

topic-defs:
  messageEventTopicDefinition: '1:3'

---
spring:
  profiles: nomad
eureka.client.serviceUrl.defaultZone: "http://${service.registry.server.ip}:${service.registry.server.port}/eureka/"

topic-defs:
  messageEventTopicDefinition: '8:3'