server:
  port: 7451

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
---
spring:
  profiles: nomad

eureka.client.serviceUrl.defaultZone: "http://${service.registry.server.ip}:${service.registry.server.port}/eureka/"

---
spring:
  profiles:
    - docker-compose
