server:
  port: 8089

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers: "localhost:9092"

---
spring:
  profiles: nomad

eureka.client.serviceUrl.defaultZone: "http://${service.registry.server.ip}:${service.registry.server.port}/eureka/"
---
spring:
  profiles:
    - docker-compose
