jsf:
  PROJECT_STAGE: Production
#  FACELETS_LIBRARIES: /tags/tags.taglib.xml
#  primefaces:
#theme: overcast
#jsf:
#  primefaces:
#    THEME: bootstrap
#    FONT_AWESOME: true
#  bootsfaces:
#USETHEME: true