server:
  port: 8095

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring:
  data:
    neo4j:
      username: "neo4j"
      password: "test"

  kafka:
    bootstrap-servers: "localhost:9092"

---
spring:
  profiles: nomad

eureka.client.serviceUrl.defaultZone: "http://${service.registry.server.ip}:${service.registry.server.port}/eureka/"
---
spring:
  profiles:
    - docker-compose
