server:
  port: 7451

spring:
  cloud:
    service-registry.auto-registration.enabled: true
    loadbalancer:
      ribbon:
        enabled: false
---
spring:
  profiles: nomad

---
spring:
  profiles:
    - docker-compose
