server:
  port: 8095

spring:
  cloud:
    service-registry.auto-registration.enabled: true
    loadbalancer:
      ribbon:
        enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    
  data:
    neo4j:
      username: "neo4j"
      password: "test"
      uri: bolt://localhost:7687

---
spring:
  profiles: nomad

---
spring:
  profiles:
    - docker_compose
