server:
  port: 8095

spring:
  data:
    neo4j:
      username: "neo4j"
      password: "test"

  kafka:
    bootstrap-servers: "localhost:9092"

---
spring:
  profiles: nomad

---
spring:
  profiles:
    - docker-compose
